name: Release

on:
  push:
    tags:
      - '*'

jobs:
  crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish
        run: cd nescore && cargo login ${{ secrets.CRATES_TOKEN }} && cargo publish
